// SPDX-License-Identifier: Apache-2.0

use std::path::Path;

use specful::repo::validate_repository;

fn fixture(name: &str) -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name)
}

#[test]
fn flags_every_planted_defect_in_the_invalid_repository() {
    let findings = validate_repository(&fixture("invalid-repo"));
    let rendered: Vec<String> = findings.iter().map(|f| f.render()).collect();
    let combined = rendered.join("\n");

    let expected = [
        "\"superseded-by\" is a required property",
        "filename sequence 0001 does not match identifier BAD-MSRS-0002",
        "concept type \"WIDGET\" is not MSRS or MSDD",
        "filename must be NNNN-short-slug.md with a lowercase slug of at most 64 characters",
        "BAD-ADR-0002 supersedes BAD-ADR-0003, but BAD-ADR-0003 does not record superseded-by BAD-ADR-0002",
        "supersession cycle detected involving BAD-ADR-0004",
        "governed-by target BAD-ADR-0009 does not exist",
        "satisfies target BAD-REQ-0404 does not exist",
        "next-msrs-sequence 1 lags allocated identifier sequence 2",
        "next-requirement-sequence 1 lags allocated identifier sequence 1",
        "requirement BAD-REQ-0001 cites source artifact BAD-ADR-0404, which does not exist",
        "requirement BAD-REQ-0001 cites its own module BAD-MSRS-0002 as a source",
        "requirement BAD-REQ-0001 cites source path docs/specs/system/msrs/0404-missing.md, which does not exist",
        "requirement BAD-REQ-0001 cites its own file docs/specs/system/msrs/0001-service.md as a source",
    ];
    for needle in expected {
        assert!(
            combined.contains(needle),
            "missing expected finding {needle:?} in:\n{combined}"
        );
    }
}

fn copy_tree(from: &Path, to: &Path) {
    std::fs::create_dir_all(to).expect("create target dir");
    for entry in std::fs::read_dir(from).expect("read source dir").flatten() {
        let target = to.join(entry.file_name());
        if entry.path().is_dir() {
            copy_tree(&entry.path(), &target);
        } else {
            std::fs::copy(entry.path(), &target).expect("copy file");
        }
    }
}

#[test]
fn detects_stale_and_author_owned_views() {
    let scratch = Path::new(env!("CARGO_TARGET_TMPDIR")).join("drift-repo");
    if scratch.exists() {
        std::fs::remove_dir_all(&scratch).expect("clear scratch");
    }
    copy_tree(&fixture("valid-repo"), &scratch);

    let catalog = scratch.join(".specful/generated/catalog.json");
    let mut content = std::fs::read_to_string(&catalog).expect("read catalog");
    content.push('\n');
    std::fs::write(&catalog, content).expect("write catalog");
    let index = scratch.join("docs/specs/system/index.md");
    let stripped = std::fs::read_to_string(&index)
        .expect("read index")
        .lines()
        .skip(1)
        .collect::<Vec<_>>()
        .join("\n");
    std::fs::write(&index, stripped).expect("write index");

    let findings = validate_repository(&scratch);
    let combined = findings
        .iter()
        .map(|f| f.render())
        .collect::<Vec<_>>()
        .join("\n");
    assert!(
        combined.contains("generated view is stale; run specful index"),
        "missing stale finding in:\n{combined}"
    );
    assert!(
        combined.contains("author-owned index.md must be removed"),
        "missing author-owned finding in:\n{combined}"
    );
}

#[test]
fn detects_and_removes_orphaned_views() {
    let scratch = Path::new(env!("CARGO_TARGET_TMPDIR")).join("orphan-repo");
    if scratch.exists() {
        std::fs::remove_dir_all(&scratch).expect("clear scratch");
    }
    copy_tree(&fixture("valid-repo"), &scratch);

    let dead_scope = scratch.join("docs/specs/dead");
    std::fs::create_dir_all(&dead_scope).expect("create dead scope");
    std::fs::write(
        dead_scope.join("index.md"),
        "<!-- Generated by specful index. Do not edit. -->\n\n# dead\n",
    )
    .expect("write orphan index");

    let findings = validate_repository(&scratch);
    let combined = findings
        .iter()
        .map(|f| f.render())
        .collect::<Vec<_>>()
        .join("\n");
    assert!(
        combined.contains("docs/specs/dead/index.md: orphaned generated view"),
        "missing orphan finding in:\n{combined}"
    );

    let index_findings = specful::index::run_index(&scratch, false);
    assert!(index_findings.is_empty(), "index should succeed");
    assert!(
        !dead_scope.join("index.md").exists(),
        "orphaned view should be deleted"
    );
    assert!(
        validate_repository(&scratch).is_empty(),
        "repository should be clean after regeneration"
    );
}

#[test]
fn collection_failures_leave_generated_views_unchanged() {
    let scratch = copy_fixture("valid-repo", "collection-failure");
    let view_paths = [
        ".specful/generated/catalog.json",
        "docs/specs/index.md",
        "docs/specs/backend/index.md",
        "docs/specs/system/index.md",
    ];
    let original_views =
        view_paths.map(|path| std::fs::read(scratch.join(path)).expect("read generated view"));

    std::fs::write(
        scratch.join("docs/specs/system/msrs/0001-progress-sync.md"),
        "invalid frontmatter\n",
    )
    .expect("corrupt source artifact");

    let findings = specful::index::run_index(&scratch, false);
    assert!(
        findings.iter().any(|finding| {
            finding
                .render()
                .contains("frontmatter must open with --- on the first line")
        }),
        "index should report the collection failure"
    );
    for (path, original) in view_paths.into_iter().zip(original_views) {
        assert_eq!(
            std::fs::read(scratch.join(path)).expect("read generated view after failed index"),
            original,
            "collection failure changed {path}"
        );
    }
}

#[test]
#[cfg(unix)]
fn does_not_delete_a_marker_bearing_file_reached_through_a_symlink() {
    let scratch = Path::new(env!("CARGO_TARGET_TMPDIR")).join("symlink-orphan-repo");
    if scratch.exists() {
        std::fs::remove_dir_all(&scratch).expect("clear scratch");
    }
    copy_tree(&fixture("valid-repo"), &scratch);

    let outside = Path::new(env!("CARGO_TARGET_TMPDIR")).join("symlink-orphan-outside");
    if outside.exists() {
        std::fs::remove_dir_all(&outside).expect("clear outside scratch");
    }
    std::fs::create_dir_all(&outside).expect("create outside dir");
    let outside_index = outside.join("index.md");
    let original = "<!-- Generated by specful index. Do not edit. -->\n\n# outside\n";
    std::fs::write(&outside_index, original).expect("write marker-bearing file outside repo");

    std::os::unix::fs::symlink(&outside, scratch.join("docs/specs/linked"))
        .expect("create symlink under docs/specs");

    let findings = specful::index::run_index(&scratch, false);
    assert_eq!(
        std::fs::read_to_string(&outside_index).expect("read outside index"),
        original,
        "marker-bearing file outside the repository must not change"
    );
    assert!(
        findings
            .iter()
            .any(|f| f.render() == "docs/specs/linked: symlink not allowed"),
        "expected a symlink finding, got: {findings:?}"
    );
}

#[test]
#[cfg(unix)]
fn does_not_write_an_expected_index_through_a_symlink() {
    let scratch = copy_fixture("valid-repo", "symlink-index-output");
    let index = scratch.join("docs/specs/system/index.md");
    std::fs::remove_file(&index).expect("remove generated index");
    let outside = scratch.with_extension("outside-index");
    let original = "<!-- Generated by specful index. Do not edit. -->\n\n# outside\n";
    std::fs::write(&outside, original).expect("write outside file");
    std::os::unix::fs::symlink(&outside, &index).expect("create output symlink");

    let findings = specful::index::run_index(&scratch, false);
    assert_eq!(
        std::fs::read_to_string(&outside).expect("read outside file"),
        original,
        "expected index must not be written through a symlink"
    );
    assert!(
        findings
            .iter()
            .any(|f| f.render() == "docs/specs/system/index.md: symlink not allowed"),
        "expected a symlink finding, got: {findings:?}"
    );
}

#[test]
#[cfg(unix)]
fn does_not_write_the_catalog_through_a_symlink() {
    let scratch = copy_fixture("valid-repo", "symlink-catalog-output");
    let catalog = scratch.join(".specful/generated/catalog.json");
    std::fs::remove_file(&catalog).expect("remove generated catalog");
    let outside = scratch.with_extension("outside-catalog");
    let original = "outside catalog\n";
    std::fs::write(&outside, original).expect("write outside file");
    std::os::unix::fs::symlink(&outside, &catalog).expect("create output symlink");

    let findings = specful::index::run_index(&scratch, false);
    assert_eq!(
        std::fs::read_to_string(&outside).expect("read outside file"),
        original,
        "catalog must not be written through a symlink"
    );
    assert!(
        findings
            .iter()
            .any(|f| f.render() == ".specful/generated/catalog.json: symlink not allowed"),
        "expected a symlink finding, got: {findings:?}"
    );
}

#[test]
#[cfg(unix)]
fn does_not_write_the_catalog_through_a_symlinked_parent() {
    let scratch = copy_fixture("valid-repo", "symlink-catalog-parent");
    let generated = scratch.join(".specful/generated");
    std::fs::remove_dir_all(&generated).expect("remove generated directory");
    let outside = scratch.with_extension("outside-generated");
    std::fs::create_dir_all(&outside).expect("create outside directory");
    let outside_catalog = outside.join("catalog.json");
    let original = "outside catalog\n";
    std::fs::write(&outside_catalog, original).expect("write outside file");
    std::os::unix::fs::symlink(&outside, &generated).expect("create parent symlink");

    let findings = specful::index::run_index(&scratch, false);
    assert_eq!(
        std::fs::read_to_string(&outside_catalog).expect("read outside file"),
        original,
        "catalog must not be written through a symlinked parent"
    );
    assert!(
        findings
            .iter()
            .any(|f| f.render() == ".specful/generated: symlink not allowed"),
        "expected a symlink finding, got: {findings:?}"
    );
}

#[test]
fn init_and_new_produce_a_schema_conformant_draft() {
    let scratch = Path::new(env!("CARGO_TARGET_TMPDIR")).join("authoring-repo");
    if scratch.exists() {
        std::fs::remove_dir_all(&scratch).expect("clear scratch");
    }
    std::fs::create_dir_all(&scratch).expect("create scratch");

    let created = specful::authoring::init(&scratch, "TST").expect("init succeeds");
    assert!(created.iter().any(|p| p == ".specful.yaml"));
    assert!(
        specful::authoring::init(&scratch, "TST").is_err(),
        "second init must refuse"
    );
    assert!(
        validate_repository(&scratch).is_empty(),
        "freshly initialized repository should be clean"
    );

    use specful::authoring::{NewKind, new_artifact};
    let adr = new_artifact(&scratch, NewKind::Adr, None, "Adopt event replay").expect("new adr");
    assert_eq!(adr, "docs/adr/0001-adopt-event-replay.md");
    let msrs = new_artifact(
        &scratch,
        NewKind::Msrs,
        Some("backend/sync"),
        "Sync requirements",
    )
    .expect("new msrs");
    assert_eq!(
        msrs,
        "docs/specs/backend/sync/msrs/0001-sync-requirements.md"
    );
    let msdd = new_artifact(&scratch, NewKind::Msdd, Some("backend/sync"), "Sync design")
        .expect("new msdd");
    assert_eq!(msdd, "docs/specs/backend/sync/msdd/0001-sync-design.md");
    assert!(
        new_artifact(&scratch, NewKind::Msdd, None, "No scope").is_err(),
        "module without scope must refuse"
    );

    let config = std::fs::read_to_string(scratch.join(".specful.yaml")).expect("read config");
    assert!(config.contains("next-adr-sequence: 2"));
    assert!(config.contains("next-msrs-sequence: 2"));
    assert!(config.contains("next-requirement-sequence: 2"));
    assert!(config.contains("next-msdd-sequence: 2"));

    // Drafts conform to the schemas and integrity rules; every remaining
    // finding is authoring work (placeholders, missing generated views),
    // never a schema defect.
    let combined = validate_repository(&scratch)
        .iter()
        .map(|f| f.render())
        .collect::<Vec<_>>()
        .join("\n");
    assert!(
        !combined.contains("frontmatter"),
        "drafts must be schema-conformant, got:\n{combined}"
    );
    assert!(
        combined.contains("placeholder"),
        "drafts should report their unfinished placeholders:\n{combined}"
    );
    assert!(
        combined.contains("decision-makers") && combined.contains("placeholder residue"),
        "an unfilled ADR decision-makers frontmatter field should be reported, not silently \
         accepted just because placeholder scanning only looked at the body:\n{combined}"
    );

    let index_findings = specful::index::run_index(&scratch, false);
    assert!(index_findings.is_empty(), "index generation should succeed");
    let after_index = validate_repository(&scratch)
        .iter()
        .map(|f| f.render())
        .collect::<Vec<_>>()
        .join("\n");
    assert!(
        !after_index.contains("generated view"),
        "views should be current after index:\n{after_index}"
    );
}

fn run_specful(args: &[&str]) -> (bool, String) {
    let output = std::process::Command::new(env!("CARGO_BIN_EXE_specful"))
        .args(args)
        .output()
        .expect("run specful binary");
    let combined = format!(
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    (output.status.success(), combined)
}

#[test]
fn shows_an_msdd_record() {
    let root = fixture("valid-repo");
    let (ok, out) = run_specful(&[
        "show",
        "OK-MSDD-0001",
        "--root",
        root.to_str().expect("utf8 path"),
    ]);
    assert!(ok, "show should succeed:\n{out}");
    assert_eq!(
        out,
        "id: OK-MSDD-0001\n\
kind: msdd\n\
title: Progress pipeline\n\
path: docs/specs/backend/msdd/0001-progress-pipeline.md\n\
governed-by: OK-ADR-0001\n\
satisfies: OK-REQ-0001, OK-REQ-0002\n"
    );
}

#[test]
fn shows_a_requirement_and_its_owning_module() {
    let root = fixture("valid-repo");
    let (ok, out) = run_specful(&[
        "show",
        "OK-REQ-0001",
        "--root",
        root.to_str().expect("utf8 path"),
    ]);
    assert!(ok, "show should succeed:\n{out}");
    assert_eq!(
        out,
        "id: OK-REQ-0001\n\
kind: requirement\n\
module: OK-MSRS-0001 (docs/specs/system/msrs/0001-progress-sync.md)\n"
    );
}

#[test]
fn traces_an_msrs_module_to_its_designs() {
    let root = fixture("valid-repo");
    let (ok, out) = run_specful(&[
        "trace",
        "OK-MSRS-0001",
        "--root",
        root.to_str().expect("utf8 path"),
    ]);
    assert!(ok, "trace should succeed:\n{out}");
    assert_eq!(
        out,
        "OK-REQ-0001 <- OK-MSDD-0001\nOK-REQ-0002 <- OK-MSDD-0001\n"
    );
}

#[test]
fn traces_a_requirement_to_its_satisfying_designs() {
    let root = fixture("valid-repo");
    let (ok, out) = run_specful(&[
        "trace",
        "OK-REQ-0001",
        "--root",
        root.to_str().expect("utf8 path"),
    ]);
    assert!(ok, "trace should succeed:\n{out}");
    assert_eq!(
        out,
        "OK-MSDD-0001 (docs/specs/backend/msdd/0001-progress-pipeline.md)\n"
    );
}

#[test]
fn traces_an_msdd_module_to_the_requirements_it_satisfies() {
    let root = fixture("valid-repo");
    let (ok, out) = run_specful(&[
        "trace",
        "OK-MSDD-0001",
        "--root",
        root.to_str().expect("utf8 path"),
    ]);
    assert!(ok, "trace should succeed:\n{out}");
    assert_eq!(
        out,
        "OK-REQ-0001 -> OK-MSRS-0001\nOK-REQ-0002 -> OK-MSRS-0001\n"
    );
}

#[test]
fn trace_of_an_adr_is_rejected() {
    let root = fixture("valid-repo");
    let (ok, out) = run_specful(&[
        "trace",
        "OK-ADR-0001",
        "--root",
        root.to_str().expect("utf8 path"),
    ]);
    assert!(!ok, "trace of an ADR must fail");
    assert!(
        out.contains("trace is not defined for ADRs; use specful show"),
        "unexpected output:\n{out}"
    );
}

#[test]
fn trace_of_unknown_identifier_fails() {
    let root = fixture("valid-repo");
    let (ok, out) = run_specful(&[
        "trace",
        "OK-MSRS-9999",
        "--root",
        root.to_str().expect("utf8 path"),
    ]);
    assert!(!ok, "trace of an unknown id must fail");
    assert!(
        out.contains("unknown identifier OK-MSRS-9999"),
        "unexpected output:\n{out}"
    );
}

#[test]
fn trace_of_an_unrecognized_kind_identifier_fails() {
    // "FOO" is not ADR, MSRS, MSDD, or REQ: infer_kind returns None before
    // any catalog lookup, a different path than a well-formed but absent id.
    let root = fixture("valid-repo");
    let (ok, out) = run_specful(&[
        "trace",
        "OK-FOO-0001",
        "--root",
        root.to_str().expect("utf8 path"),
    ]);
    assert!(!ok, "trace of an unrecognized-kind id must fail");
    assert!(
        out.contains("unknown identifier OK-FOO-0001"),
        "unexpected output:\n{out}"
    );
}

/// Writes a hand-built catalog directly, bypassing `specful index`: query.rs
/// reads the catalog only, so this is enough to exercise result shapes
/// (untraced requirements, an MSDD with no satisfies links) that the
/// `valid-repo` fixture's fully-linked artifacts never produce.
fn scratch_catalog(artifacts_json: &str) -> tempfile::TempDir {
    let root = tempfile::tempdir().expect("create scratch");
    std::fs::create_dir_all(root.path().join(".specful/generated")).expect("create catalog dir");
    std::fs::write(
        root.path().join(".specful/generated/catalog.json"),
        format!("{{\"artifacts\": {artifacts_json}}}"),
    )
    .expect("write catalog");
    root
}

#[test]
fn traces_an_msrs_module_with_an_unsatisfied_requirement_as_untraced() {
    let root = scratch_catalog(
        r#"[
            {
                "id": "T-MSRS-0001",
                "kind": "msrs",
                "path": "docs/specs/system/msrs/0001-x.md",
                "title": "X",
                "requirements": ["T-REQ-0001"]
            }
        ]"#,
    );
    let (ok, out) = run_specful(&[
        "trace",
        "T-MSRS-0001",
        "--root",
        root.path().to_str().expect("utf8 path"),
    ]);
    assert!(ok, "trace should succeed:\n{out}");
    assert_eq!(out, "T-REQ-0001 <- (untraced)\n");
}

#[test]
fn traces_an_unsatisfied_requirement_as_untraced() {
    let root = scratch_catalog(
        r#"[
            {
                "id": "T-MSRS-0001",
                "kind": "msrs",
                "path": "docs/specs/system/msrs/0001-x.md",
                "title": "X",
                "requirements": ["T-REQ-0001"]
            }
        ]"#,
    );
    let (ok, out) = run_specful(&[
        "trace",
        "T-REQ-0001",
        "--root",
        root.path().to_str().expect("utf8 path"),
    ]);
    assert!(ok, "trace should succeed:\n{out}");
    assert_eq!(out, "(untraced)\n");
}

#[test]
fn traces_an_msdd_module_with_no_satisfies_links() {
    let root = scratch_catalog(
        r#"[
            {
                "id": "T-MSDD-0001",
                "kind": "msdd",
                "path": "docs/specs/system/msdd/0001-y.md",
                "title": "Y",
                "satisfies": []
            }
        ]"#,
    );
    let (ok, out) = run_specful(&[
        "trace",
        "T-MSDD-0001",
        "--root",
        root.path().to_str().expect("utf8 path"),
    ]);
    assert!(ok, "trace should succeed:\n{out}");
    assert_eq!(out, "(no satisfies links)\n");
}

#[test]
fn traces_an_msrs_module_with_no_requirements() {
    let root = scratch_catalog(
        r#"[
            {
                "id": "T-MSRS-0001",
                "kind": "msrs",
                "path": "docs/specs/system/msrs/0001-x.md",
                "title": "X",
                "requirements": []
            }
        ]"#,
    );
    let (ok, out) = run_specful(&[
        "trace",
        "T-MSRS-0001",
        "--root",
        root.path().to_str().expect("utf8 path"),
    ]);
    assert!(ok, "trace should succeed:\n{out}");
    assert_eq!(out, "(no requirements)\n");
}

#[test]
fn show_of_unknown_identifier_fails() {
    let root = fixture("valid-repo");
    let (ok, out) = run_specful(&[
        "show",
        "OK-MSDD-9999",
        "--root",
        root.to_str().expect("utf8 path"),
    ]);
    assert!(!ok, "show of an unknown id must fail");
    assert!(
        out.contains("unknown identifier OK-MSDD-9999"),
        "unexpected output:\n{out}"
    );
}

#[test]
fn show_of_unknown_requirement_identifier_fails() {
    let root = fixture("valid-repo");
    let (ok, out) = run_specful(&[
        "show",
        "OK-REQ-9999",
        "--root",
        root.to_str().expect("utf8 path"),
    ]);
    assert!(!ok, "show of an unknown requirement id must fail");
    assert!(
        out.contains("unknown identifier OK-REQ-9999"),
        "unexpected output:\n{out}"
    );
}

#[test]
fn shows_an_adr_record_with_supersession_links() {
    let root = scratch_catalog(
        r#"[
            {
                "id": "T-ADR-0002",
                "kind": "adr",
                "path": "docs/adr/0002-adopt-x.md",
                "title": "Adopt X",
                "status": "accepted",
                "supersedes": ["T-ADR-0001"],
                "superseded-by": ["T-ADR-0003"]
            }
        ]"#,
    );
    let (ok, out) = run_specful(&[
        "show",
        "T-ADR-0002",
        "--root",
        root.path().to_str().expect("utf8 path"),
    ]);
    assert!(ok, "show should succeed:\n{out}");
    assert_eq!(
        out,
        "id: T-ADR-0002\n\
kind: adr\n\
title: Adopt X\n\
path: docs/adr/0002-adopt-x.md\n\
status: accepted\n\
supersedes: T-ADR-0001\n\
superseded-by: T-ADR-0003\n"
    );
}

#[test]
fn show_with_a_corrupt_catalog_reports_a_json_error() {
    let root = tempfile::tempdir().expect("create scratch");
    std::fs::create_dir_all(root.path().join(".specful/generated")).expect("create catalog dir");
    std::fs::write(
        root.path().join(".specful/generated/catalog.json"),
        "not valid json",
    )
    .expect("write corrupt catalog");

    let (ok, out) = run_specful(&[
        "show",
        "OK-MSDD-0001",
        "--root",
        root.path().to_str().expect("utf8 path"),
    ]);
    assert!(!ok, "show with a corrupt catalog must fail");
    assert!(
        out.contains("catalog is not valid JSON; run specful index"),
        "unexpected output:\n{out}"
    );
}

#[test]
fn show_without_a_catalog_reports_the_run_index_message() {
    let scratch = Path::new(env!("CARGO_TARGET_TMPDIR")).join("no-catalog-repo");
    if scratch.exists() {
        std::fs::remove_dir_all(&scratch).expect("clear scratch");
    }
    copy_tree(&fixture("valid-repo"), &scratch);
    std::fs::remove_file(scratch.join(".specful/generated/catalog.json")).expect("remove catalog");

    let (ok, out) = run_specful(&[
        "show",
        "OK-MSDD-0001",
        "--root",
        scratch.to_str().expect("utf8 path"),
    ]);
    assert!(!ok, "show without a catalog must fail");
    assert!(
        out.contains("missing catalog; run specful index"),
        "unexpected output:\n{out}"
    );
}

#[test]
fn accepts_the_valid_repository() {
    let findings = validate_repository(&fixture("valid-repo"));
    let rendered: Vec<String> = findings.iter().map(|f| f.render()).collect();
    assert!(
        findings.is_empty(),
        "expected no findings, got:\n{}",
        rendered.join("\n")
    );
}

#[test]
fn rejects_a_non_kebab_case_specification_scope() {
    let scratch = copy_fixture("valid-repo", "invalid-scope");
    std::fs::rename(
        scratch.join("docs/specs/system"),
        scratch.join("docs/specs/Data Plane"),
    )
    .expect("rename scope");

    let findings = validate_repository(&scratch);
    let rendered: Vec<String> = findings.iter().map(|f| f.render()).collect();
    assert!(
        rendered.iter().any(|f| f.contains(
            "docs/specs/Data Plane/msrs/0001-progress-sync.md: scope directory segment \"Data Plane\" must be lowercase ASCII kebab-case"
        )),
        "expected an invalid scope finding, got:\n{}",
        rendered.join("\n")
    );
}

#[test]
fn does_not_apply_scope_naming_rules_outside_docs_specs() {
    let scratch = copy_fixture("valid-repo", "unrelated-directory");
    std::fs::create_dir_all(scratch.join("reports/Data Plane"))
        .expect("create unrelated directory");

    let findings = validate_repository(&scratch);
    assert!(
        findings.is_empty(),
        "unrelated directories must not be treated as specification scopes: {findings:?}"
    );
}

/// Copies a fixture tree into a fresh temporary directory and returns it.
fn copy_fixture(name: &str, label: &str) -> std::path::PathBuf {
    fn copy_tree(from: &Path, to: &Path) {
        std::fs::create_dir_all(to).expect("create directory");
        for entry in std::fs::read_dir(from).expect("read fixture directory") {
            let entry = entry.expect("read fixture entry");
            let target = to.join(entry.file_name());
            if entry.file_type().expect("entry type").is_dir() {
                copy_tree(&entry.path(), &target);
            } else {
                std::fs::copy(entry.path(), &target).expect("copy fixture file");
            }
        }
    }

    let unique = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .expect("clock is after the epoch")
        .as_nanos();
    let root = std::path::PathBuf::from(env!("CARGO_TARGET_TMPDIR"))
        .join(format!("specful-{label}-{unique}"));
    let _ = std::fs::remove_dir_all(&root);
    copy_tree(&fixture(name), &root);
    root
}

#[cfg(unix)]
#[test]
fn reports_symlinks_without_following_them() {
    let root = copy_fixture("valid-repo", "symlink");
    // Points back at an ancestor: following it would never terminate.
    std::os::unix::fs::symlink("../../..", root.join("docs/specs/system/loop"))
        .expect("create symlink");

    let findings = validate_repository(&root);
    let rendered: Vec<String> = findings.iter().map(|f| f.render()).collect();
    std::fs::remove_dir_all(&root).expect("remove temporary repository");

    assert!(
        rendered
            .iter()
            .any(|f| f == "docs/specs/system/loop: symlink not allowed"),
        "expected a symlink finding, got:\n{}",
        rendered.join("\n")
    );
}

#[cfg(unix)]
#[test]
fn rejects_a_path_source_whose_final_component_is_a_symlink_outside_the_repository() {
    let root = copy_fixture("valid-repo", "symlink-final");
    let cited = root.join("docs/adr/0001-store-progress-events.md");
    std::fs::remove_file(&cited).expect("remove cited file");

    let outside =
        std::path::PathBuf::from(env!("CARGO_TARGET_TMPDIR")).join("specful-symlink-final-target");
    std::fs::write(&outside, "outside the repository").expect("write outside file");
    std::os::unix::fs::symlink(&outside, &cited).expect("create symlink");

    let findings = validate_repository(&root);
    let rendered: Vec<String> = findings.iter().map(|f| f.render()).collect();
    std::fs::remove_dir_all(&root).expect("remove temporary repository");
    let _ = std::fs::remove_file(&outside);

    assert!(
        rendered.iter().any(|f| f.contains(
            "requirement OK-REQ-0001 cites source path docs/adr/0001-store-progress-events.md, which does not exist"
        )),
        "expected a finding for the symlinked source, got:\n{}",
        rendered.join("\n")
    );
}

#[cfg(unix)]
#[test]
fn rejects_a_path_source_through_a_symlinked_intermediate_directory() {
    let root = copy_fixture("valid-repo", "symlink-intermediate");
    let real_dir = root.join("docs/adr-real");
    std::fs::rename(root.join("docs/adr"), &real_dir).expect("rename adr directory");
    std::os::unix::fs::symlink(&real_dir, root.join("docs/adr")).expect("create symlink");

    let findings = validate_repository(&root);
    let rendered: Vec<String> = findings.iter().map(|f| f.render()).collect();
    std::fs::remove_dir_all(&real_dir).expect("remove real directory");
    let _ = std::fs::remove_file(root.join("docs/adr"));
    std::fs::remove_dir_all(&root).expect("remove temporary repository");

    assert!(
        rendered.iter().any(|f| f.contains(
            "requirement OK-REQ-0001 cites source path docs/adr/0001-store-progress-events.md, which does not exist"
        )),
        "expected a finding for the symlinked intermediate directory, got:\n{}",
        rendered.join("\n")
    );
}

#[cfg(unix)]
#[test]
fn reports_unreadable_directories() {
    use std::os::unix::fs::PermissionsExt;

    /// Restores readable permissions even when the assertions panic.
    struct Restore(std::path::PathBuf);
    impl Drop for Restore {
        fn drop(&mut self) {
            let _ = std::fs::set_permissions(&self.0, std::fs::Permissions::from_mode(0o755));
            let _ =
                std::fs::remove_dir_all(self.0.parent().and_then(Path::parent).unwrap_or(&self.0));
        }
    }

    let root = copy_fixture("valid-repo", "unreadable");
    let locked = root.join("docs/adr");
    std::fs::set_permissions(&locked, std::fs::Permissions::from_mode(0o000))
        .expect("remove directory permissions");
    let _restore = Restore(locked);

    let findings = validate_repository(&root);
    let rendered: Vec<String> = findings.iter().map(|f| f.render()).collect();
    assert!(
        rendered
            .iter()
            .any(|f| f.starts_with("docs/adr: cannot read directory")),
        "expected an unreadable directory finding, got:\n{}",
        rendered.join("\n")
    );
}
