// SPDX-License-Identifier: Apache-2.0

use std::path::Path;

use specful::repo::validate_repository;

fn fixture(name: &str) -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name)
}

#[test]
fn flags_every_planted_defect_in_the_invalid_repository() {
    let findings = validate_repository(&fixture("invalid-repo"));
    let rendered: Vec<String> = findings.iter().map(|f| f.render()).collect();
    let combined = rendered.join("\n");

    let expected = [
        "\"superseded-by\" is a required property",
        "filename sequence 0001 does not match identifier BAD-MSRS-0002",
        "concept type \"WIDGET\" is not MSRS or MSDD",
        "filename must be NNNN-short-slug.md with a lowercase slug of at most 64 characters",
        "BAD-ADR-0002 supersedes BAD-ADR-0003, but BAD-ADR-0003 does not record superseded-by BAD-ADR-0002",
        "supersession cycle detected involving BAD-ADR-0004",
        "governed-by target BAD-ADR-0009 does not exist",
        "satisfies target BAD-REQ-0404 does not exist",
        "next-msrs-sequence 1 lags allocated identifier sequence 2",
        "next-requirement-sequence 1 lags allocated identifier sequence 1",
        "requirement BAD-REQ-0001 cites source artifact BAD-ADR-0404, which does not exist",
        "requirement BAD-REQ-0001 cites its own module BAD-MSRS-0002 as a source",
        "requirement BAD-REQ-0001 cites source path docs/specs/system/msrs/0404-missing.md, which does not exist",
        "requirement BAD-REQ-0001 cites its own file docs/specs/system/msrs/0001-service.md as a source",
    ];
    for needle in expected {
        assert!(
            combined.contains(needle),
            "missing expected finding {needle:?} in:\n{combined}"
        );
    }
}

fn copy_tree(from: &Path, to: &Path) {
    std::fs::create_dir_all(to).expect("create target dir");
    for entry in std::fs::read_dir(from).expect("read source dir").flatten() {
        let target = to.join(entry.file_name());
        if entry.path().is_dir() {
            copy_tree(&entry.path(), &target);
        } else {
            std::fs::copy(entry.path(), &target).expect("copy file");
        }
    }
}

#[test]
fn detects_stale_and_author_owned_views() {
    let scratch = Path::new(env!("CARGO_TARGET_TMPDIR")).join("drift-repo");
    if scratch.exists() {
        std::fs::remove_dir_all(&scratch).expect("clear scratch");
    }
    copy_tree(&fixture("valid-repo"), &scratch);

    let catalog = scratch.join(".specful/generated/catalog.json");
    let mut content = std::fs::read_to_string(&catalog).expect("read catalog");
    content.push('\n');
    std::fs::write(&catalog, content).expect("write catalog");
    let index = scratch.join("docs/specs/system/index.md");
    let stripped = std::fs::read_to_string(&index)
        .expect("read index")
        .lines()
        .skip(1)
        .collect::<Vec<_>>()
        .join("\n");
    std::fs::write(&index, stripped).expect("write index");

    let findings = validate_repository(&scratch);
    let combined = findings
        .iter()
        .map(|f| f.render())
        .collect::<Vec<_>>()
        .join("\n");
    assert!(
        combined.contains("generated view is stale; run specful index"),
        "missing stale finding in:\n{combined}"
    );
    assert!(
        combined.contains("author-owned index.md must be removed"),
        "missing author-owned finding in:\n{combined}"
    );
}

#[test]
fn detects_and_removes_orphaned_views() {
    let scratch = Path::new(env!("CARGO_TARGET_TMPDIR")).join("orphan-repo");
    if scratch.exists() {
        std::fs::remove_dir_all(&scratch).expect("clear scratch");
    }
    copy_tree(&fixture("valid-repo"), &scratch);

    let dead_scope = scratch.join("docs/specs/dead");
    std::fs::create_dir_all(&dead_scope).expect("create dead scope");
    std::fs::write(
        dead_scope.join("index.md"),
        "<!-- Generated by specful index. Do not edit. -->\n\n# dead\n",
    )
    .expect("write orphan index");

    let findings = validate_repository(&scratch);
    let combined = findings
        .iter()
        .map(|f| f.render())
        .collect::<Vec<_>>()
        .join("\n");
    assert!(
        combined.contains("docs/specs/dead/index.md: orphaned generated view"),
        "missing orphan finding in:\n{combined}"
    );

    let index_findings = specful::index::run_index(&scratch, false);
    assert!(index_findings.is_empty(), "index should succeed");
    assert!(
        !dead_scope.join("index.md").exists(),
        "orphaned view should be deleted"
    );
    assert!(
        validate_repository(&scratch).is_empty(),
        "repository should be clean after regeneration"
    );
}

#[test]
#[cfg(unix)]
fn does_not_delete_a_marker_bearing_file_reached_through_a_symlink() {
    let scratch = Path::new(env!("CARGO_TARGET_TMPDIR")).join("symlink-orphan-repo");
    if scratch.exists() {
        std::fs::remove_dir_all(&scratch).expect("clear scratch");
    }
    copy_tree(&fixture("valid-repo"), &scratch);

    let outside = Path::new(env!("CARGO_TARGET_TMPDIR")).join("symlink-orphan-outside");
    if outside.exists() {
        std::fs::remove_dir_all(&outside).expect("clear outside scratch");
    }
    std::fs::create_dir_all(&outside).expect("create outside dir");
    let outside_index = outside.join("index.md");
    let original = "<!-- Generated by specful index. Do not edit. -->\n\n# outside\n";
    std::fs::write(&outside_index, original).expect("write marker-bearing file outside repo");

    std::os::unix::fs::symlink(&outside, scratch.join("docs/specs/linked"))
        .expect("create symlink under docs/specs");

    let findings = specful::index::run_index(&scratch, false);
    assert_eq!(
        std::fs::read_to_string(&outside_index).expect("read outside index"),
        original,
        "marker-bearing file outside the repository must not change"
    );
    assert!(
        findings
            .iter()
            .any(|f| f.render() == "docs/specs/linked: symlink not allowed"),
        "expected a symlink finding, got: {findings:?}"
    );
}

#[test]
#[cfg(unix)]
fn does_not_write_an_expected_index_through_a_symlink() {
    let scratch = copy_fixture("valid-repo", "symlink-index-output");
    let index = scratch.join("docs/specs/system/index.md");
    std::fs::remove_file(&index).expect("remove generated index");
    let outside = scratch.with_extension("outside-index");
    let original = "<!-- Generated by specful index. Do not edit. -->\n\n# outside\n";
    std::fs::write(&outside, original).expect("write outside file");
    std::os::unix::fs::symlink(&outside, &index).expect("create output symlink");

    let findings = specful::index::run_index(&scratch, false);
    assert_eq!(
        std::fs::read_to_string(&outside).expect("read outside file"),
        original,
        "expected index must not be written through a symlink"
    );
    assert!(
        findings
            .iter()
            .any(|f| f.render() == "docs/specs/system/index.md: symlink not allowed"),
        "expected a symlink finding, got: {findings:?}"
    );
}

#[test]
#[cfg(unix)]
fn does_not_write_the_catalog_through_a_symlink() {
    let scratch = copy_fixture("valid-repo", "symlink-catalog-output");
    let catalog = scratch.join(".specful/generated/catalog.json");
    std::fs::remove_file(&catalog).expect("remove generated catalog");
    let outside = scratch.with_extension("outside-catalog");
    let original = "outside catalog\n";
    std::fs::write(&outside, original).expect("write outside file");
    std::os::unix::fs::symlink(&outside, &catalog).expect("create output symlink");

    let findings = specful::index::run_index(&scratch, false);
    assert_eq!(
        std::fs::read_to_string(&outside).expect("read outside file"),
        original,
        "catalog must not be written through a symlink"
    );
    assert!(
        findings
            .iter()
            .any(|f| f.render() == ".specful/generated/catalog.json: symlink not allowed"),
        "expected a symlink finding, got: {findings:?}"
    );
}

#[test]
#[cfg(unix)]
fn does_not_write_the_catalog_through_a_symlinked_parent() {
    let scratch = copy_fixture("valid-repo", "symlink-catalog-parent");
    let generated = scratch.join(".specful/generated");
    std::fs::remove_dir_all(&generated).expect("remove generated directory");
    let outside = scratch.with_extension("outside-generated");
    std::fs::create_dir_all(&outside).expect("create outside directory");
    let outside_catalog = outside.join("catalog.json");
    let original = "outside catalog\n";
    std::fs::write(&outside_catalog, original).expect("write outside file");
    std::os::unix::fs::symlink(&outside, &generated).expect("create parent symlink");

    let findings = specful::index::run_index(&scratch, false);
    assert_eq!(
        std::fs::read_to_string(&outside_catalog).expect("read outside file"),
        original,
        "catalog must not be written through a symlinked parent"
    );
    assert!(
        findings
            .iter()
            .any(|f| f.render() == ".specful/generated: symlink not allowed"),
        "expected a symlink finding, got: {findings:?}"
    );
}

#[test]
fn accepts_the_valid_repository() {
    let findings = validate_repository(&fixture("valid-repo"));
    let rendered: Vec<String> = findings.iter().map(|f| f.render()).collect();
    assert!(
        findings.is_empty(),
        "expected no findings, got:\n{}",
        rendered.join("\n")
    );
}

#[test]
fn rejects_a_non_kebab_case_specification_scope() {
    let scratch = copy_fixture("valid-repo", "invalid-scope");
    std::fs::rename(
        scratch.join("docs/specs/system"),
        scratch.join("docs/specs/Data Plane"),
    )
    .expect("rename scope");

    let findings = validate_repository(&scratch);
    let rendered: Vec<String> = findings.iter().map(|f| f.render()).collect();
    assert!(
        rendered.iter().any(|f| f.contains(
            "docs/specs/Data Plane/msrs/0001-progress-sync.md: scope directory segment \"Data Plane\" must be lowercase ASCII kebab-case"
        )),
        "expected an invalid scope finding, got:\n{}",
        rendered.join("\n")
    );
}

#[test]
fn does_not_apply_scope_naming_rules_outside_docs_specs() {
    let scratch = copy_fixture("valid-repo", "unrelated-directory");
    std::fs::create_dir_all(scratch.join("reports/Data Plane"))
        .expect("create unrelated directory");

    let findings = validate_repository(&scratch);
    assert!(
        findings.is_empty(),
        "unrelated directories must not be treated as specification scopes: {findings:?}"
    );
}

/// Copies a fixture tree into a fresh temporary directory and returns it.
fn copy_fixture(name: &str, label: &str) -> std::path::PathBuf {
    fn copy_tree(from: &Path, to: &Path) {
        std::fs::create_dir_all(to).expect("create directory");
        for entry in std::fs::read_dir(from).expect("read fixture directory") {
            let entry = entry.expect("read fixture entry");
            let target = to.join(entry.file_name());
            if entry.file_type().expect("entry type").is_dir() {
                copy_tree(&entry.path(), &target);
            } else {
                std::fs::copy(entry.path(), &target).expect("copy fixture file");
            }
        }
    }

    let unique = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .expect("clock is after the epoch")
        .as_nanos();
    let root = std::path::PathBuf::from(env!("CARGO_TARGET_TMPDIR"))
        .join(format!("specful-{label}-{unique}"));
    let _ = std::fs::remove_dir_all(&root);
    copy_tree(&fixture(name), &root);
    root
}

#[cfg(unix)]
#[test]
fn reports_symlinks_without_following_them() {
    let root = copy_fixture("valid-repo", "symlink");
    // Points back at an ancestor: following it would never terminate.
    std::os::unix::fs::symlink("../../..", root.join("docs/specs/system/loop"))
        .expect("create symlink");

    let findings = validate_repository(&root);
    let rendered: Vec<String> = findings.iter().map(|f| f.render()).collect();
    std::fs::remove_dir_all(&root).expect("remove temporary repository");

    assert!(
        rendered
            .iter()
            .any(|f| f == "docs/specs/system/loop: symlink not allowed"),
        "expected a symlink finding, got:\n{}",
        rendered.join("\n")
    );
}

#[cfg(unix)]
#[test]
fn rejects_a_path_source_whose_final_component_is_a_symlink_outside_the_repository() {
    let root = copy_fixture("valid-repo", "symlink-final");
    let cited = root.join("docs/adr/0001-store-progress-events.md");
    std::fs::remove_file(&cited).expect("remove cited file");

    let outside =
        std::path::PathBuf::from(env!("CARGO_TARGET_TMPDIR")).join("specful-symlink-final-target");
    std::fs::write(&outside, "outside the repository").expect("write outside file");
    std::os::unix::fs::symlink(&outside, &cited).expect("create symlink");

    let findings = validate_repository(&root);
    let rendered: Vec<String> = findings.iter().map(|f| f.render()).collect();
    std::fs::remove_dir_all(&root).expect("remove temporary repository");
    let _ = std::fs::remove_file(&outside);

    assert!(
        rendered.iter().any(|f| f.contains(
            "requirement OK-REQ-0001 cites source path docs/adr/0001-store-progress-events.md, which does not exist"
        )),
        "expected a finding for the symlinked source, got:\n{}",
        rendered.join("\n")
    );
}

#[cfg(unix)]
#[test]
fn rejects_a_path_source_through_a_symlinked_intermediate_directory() {
    let root = copy_fixture("valid-repo", "symlink-intermediate");
    let real_dir = root.join("docs/adr-real");
    std::fs::rename(root.join("docs/adr"), &real_dir).expect("rename adr directory");
    std::os::unix::fs::symlink(&real_dir, root.join("docs/adr")).expect("create symlink");

    let findings = validate_repository(&root);
    let rendered: Vec<String> = findings.iter().map(|f| f.render()).collect();
    std::fs::remove_dir_all(&real_dir).expect("remove real directory");
    let _ = std::fs::remove_file(root.join("docs/adr"));
    std::fs::remove_dir_all(&root).expect("remove temporary repository");

    assert!(
        rendered.iter().any(|f| f.contains(
            "requirement OK-REQ-0001 cites source path docs/adr/0001-store-progress-events.md, which does not exist"
        )),
        "expected a finding for the symlinked intermediate directory, got:\n{}",
        rendered.join("\n")
    );
}

#[cfg(unix)]
#[test]
fn reports_unreadable_directories() {
    use std::os::unix::fs::PermissionsExt;

    /// Restores readable permissions even when the assertions panic.
    struct Restore(std::path::PathBuf);
    impl Drop for Restore {
        fn drop(&mut self) {
            let _ = std::fs::set_permissions(&self.0, std::fs::Permissions::from_mode(0o755));
            let _ =
                std::fs::remove_dir_all(self.0.parent().and_then(Path::parent).unwrap_or(&self.0));
        }
    }

    let root = copy_fixture("valid-repo", "unreadable");
    let locked = root.join("docs/adr");
    std::fs::set_permissions(&locked, std::fs::Permissions::from_mode(0o000))
        .expect("remove directory permissions");
    let _restore = Restore(locked);

    let findings = validate_repository(&root);
    let rendered: Vec<String> = findings.iter().map(|f| f.render()).collect();
    assert!(
        rendered
            .iter()
            .any(|f| f.starts_with("docs/adr: cannot read directory")),
        "expected an unreadable directory finding, got:\n{}",
        rendered.join("\n")
    );
}
