//! Generated navigation views: per-scope index files and the machine
//! catalog. Both are derived, disposable, and drift-checked; they carry no
//! canonical knowledge.

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use serde_json::json;

use crate::body::ArtifactKind;
use crate::diagnostics::Finding;
use crate::repo::{Artifact, SPECS_DIR, collect_artifacts, read_entries};

/// First line of every generated index file. Its absence marks a file as
/// author-owned, which generation refuses to overwrite.
pub const GENERATED_MARKER: &str = "<!-- Generated by specful index. Do not edit. -->";

pub const CATALOG_PATH: &str = ".specful/generated/catalog.json";

/// Renders every generated view as repository-relative path to exact
/// content. Purely derived from the collected artifacts, so identical
/// repositories render identical bytes.
pub(crate) fn render_views(artifacts: &[Artifact]) -> BTreeMap<String, String> {
    let mut views = BTreeMap::new();
    views.insert(CATALOG_PATH.to_owned(), render_catalog(artifacts));
    for (scope, content) in render_indexes(artifacts) {
        let path = if scope.is_empty() {
            format!("{SPECS_DIR}/index.md")
        } else {
            format!("{SPECS_DIR}/{scope}/index.md")
        };
        views.insert(path, content);
    }
    views
}

fn kind_label(kind: ArtifactKind) -> &'static str {
    match kind {
        ArtifactKind::Adr => "adr",
        ArtifactKind::Requirement => "req",
        ArtifactKind::Design => "design",
    }
}

fn render_catalog(artifacts: &[Artifact]) -> String {
    let mut sorted: Vec<&Artifact> = artifacts.iter().collect();
    sorted.sort_by(|a, b| a.id.cmp(&b.id));
    let entries: Vec<serde_json::Value> = sorted
        .iter()
        .map(|artifact| {
            let mut entry = json!({
                "id": artifact.id,
                "kind": kind_label(artifact.kind),
                "path": artifact.path,
                "title": artifact.title,
            });
            let object = entry.as_object_mut().expect("entry is an object");
            if let Some(status) = &artifact.status {
                object.insert("status".to_owned(), json!(status));
            }
            for (field, values) in [
                ("supersedes", &artifact.supersedes),
                ("superseded-by", &artifact.superseded_by),
                ("satisfies", &artifact.satisfies),
                ("governed-by", &artifact.governed_by),
            ] {
                if !values.is_empty() {
                    object.insert(field.to_owned(), json!(values));
                }
            }
            entry
        })
        .collect();
    let catalog = json!({ "artifacts": entries });
    let mut rendered = serde_json::to_string_pretty(&catalog).expect("catalog serializes");
    rendered.push('\n');
    rendered
}

/// The scope of a specs module: the path segments between `docs/specs/` and
/// its artifact-kind directory. `None` for artifacts outside the tree.
fn module_scope(artifact: &Artifact) -> Option<String> {
    let rest = artifact.path.strip_prefix(&format!("{SPECS_DIR}/"))?;
    let mut segments: Vec<&str> = rest.split('/').collect();
    segments.pop()?;
    segments.pop()?;
    Some(segments.join("/"))
}

fn render_indexes(artifacts: &[Artifact]) -> BTreeMap<String, String> {
    let mut scopes: BTreeSet<String> = BTreeSet::from([String::new()]);
    let mut modules: BTreeMap<String, Vec<&Artifact>> = BTreeMap::new();
    for artifact in artifacts {
        if artifact.kind == ArtifactKind::Adr {
            continue;
        }
        let Some(scope) = module_scope(artifact) else {
            continue;
        };
        // Every ancestor scope exists so navigation can reach the module
        // from the root one link at a time.
        let mut ancestor = String::new();
        scopes.insert(ancestor.clone());
        for segment in scope.split('/').filter(|s| !s.is_empty()) {
            if !ancestor.is_empty() {
                ancestor.push('/');
            }
            ancestor.push_str(segment);
            scopes.insert(ancestor.clone());
        }
        modules.entry(scope).or_default().push(artifact);
    }

    let mut indexes = BTreeMap::new();
    for scope in &scopes {
        let children: Vec<&str> = scopes
            .iter()
            .filter_map(|other| {
                let rest = if scope.is_empty() {
                    other.as_str()
                } else {
                    other.strip_prefix(&format!("{scope}/"))?
                };
                (!rest.is_empty() && !rest.contains('/')).then_some(rest)
            })
            .collect();

        let mut content = String::new();
        content.push_str(GENERATED_MARKER);
        content.push_str("\n\n");
        if scope.is_empty() {
            content.push_str("# Specifications\n");
        } else {
            content.push_str(&format!("# {scope}\n"));
        }

        if !children.is_empty() {
            content.push_str("\n## Scopes\n\n");
            for child in children {
                content.push_str(&format!("- [{child}]({child}/index.md)\n"));
            }
        }

        let empty = Vec::new();
        let scope_modules = modules.get(scope).unwrap_or(&empty);
        for (kind, heading) in [
            (ArtifactKind::Requirement, "Requirements"),
            (ArtifactKind::Design, "Designs"),
        ] {
            let mut of_kind: Vec<&&Artifact> =
                scope_modules.iter().filter(|a| a.kind == kind).collect();
            of_kind.sort_by(|a, b| a.id.cmp(&b.id));
            if of_kind.is_empty() {
                continue;
            }
            content.push_str(&format!("\n## {heading}\n\n"));
            for artifact in of_kind {
                let prefix = if scope.is_empty() {
                    format!("{SPECS_DIR}/")
                } else {
                    format!("{SPECS_DIR}/{scope}/")
                };
                let link = artifact
                    .path
                    .strip_prefix(&prefix)
                    .unwrap_or(&artifact.path);
                content.push_str(&format!(
                    "- [{}]({link}): {}\n",
                    artifact.id, artifact.title
                ));
            }
        }
        indexes.insert(scope.clone(), content);
    }
    indexes
}

fn output_path_is_safe(root: &Path, path: &str, findings: &mut Vec<Finding>) -> bool {
    let mut current = root.to_path_buf();
    for component in Path::new(path).components() {
        current.push(component);
        match std::fs::symlink_metadata(&current) {
            Ok(metadata) if metadata.file_type().is_symlink() => {
                let unsafe_path = current
                    .strip_prefix(root)
                    .unwrap_or(&current)
                    .components()
                    .map(|c| c.as_os_str().to_string_lossy())
                    .collect::<Vec<_>>()
                    .join("/");
                if !findings
                    .iter()
                    .any(|f| f.path == unsafe_path && f.message == "symlink not allowed")
                {
                    findings.push(Finding::new(&unsafe_path, None, "symlink not allowed"));
                }
                return false;
            }
            Ok(_) => {}
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => return true,
            Err(error) => {
                findings.push(Finding::new(
                    path,
                    None,
                    format!("cannot inspect generated view path: {error}"),
                ));
                return false;
            }
        }
    }
    true
}

/// Committed generated views on disk: the catalog plus every marker-bearing
/// `index.md` under `docs/specs/`. Unmarked index files are author-owned and
/// are not ours to manage.
///
/// The walk and catalog check never follow symlinks, so only paths physically
/// beneath the repository are eligible for orphan removal.
fn committed_views(root: &Path, findings: &mut Vec<Finding>) -> Vec<String> {
    let mut views = Vec::new();
    if output_path_is_safe(root, CATALOG_PATH, findings) && root.join(CATALOG_PATH).is_file() {
        views.push(CATALOG_PATH.to_owned());
    }
    let mut stack = vec![root.join(SPECS_DIR)];
    while let Some(dir) = stack.pop() {
        for (path, is_dir) in read_entries(root, &dir, findings) {
            if is_dir {
                stack.push(path);
            } else if path.file_name().is_some_and(|n| n == "index.md")
                && std::fs::read_to_string(&path)
                    .is_ok_and(|content| content.starts_with(GENERATED_MARKER))
            {
                let relative = path
                    .strip_prefix(root)
                    .unwrap_or(&path)
                    .components()
                    .map(|c| c.as_os_str().to_string_lossy())
                    .collect::<Vec<_>>()
                    .join("/");
                views.push(relative);
            }
        }
    }
    views.sort();
    views
}

/// Compares committed generated views against a fresh render, appending
/// findings for missing, stale, author-owned, or orphaned files.
pub(crate) fn check_generated_views(
    root: &Path,
    artifacts: &[Artifact],
    findings: &mut Vec<Finding>,
) {
    let expected_views = render_views(artifacts);
    for committed in committed_views(root, findings) {
        if !expected_views.contains_key(&committed) {
            findings.push(Finding::new(
                &committed,
                None,
                "orphaned generated view; run specful index",
            ));
        }
    }
    for (path, expected) in expected_views {
        if !output_path_is_safe(root, &path, findings) {
            continue;
        }
        match std::fs::read_to_string(root.join(&path)) {
            Err(_) => findings.push(Finding::new(
                &path,
                None,
                "missing generated view; run specful index",
            )),
            Ok(actual) if path.ends_with("index.md") && !actual.starts_with(GENERATED_MARKER) => {
                findings.push(Finding::new(
                    &path,
                    Some(1),
                    "author-owned index.md must be removed before specful generates navigation here",
                ));
            }
            Ok(actual) if actual != expected => findings.push(Finding::new(
                &path,
                None,
                "generated view is stale; run specful index",
            )),
            Ok(_) => {}
        }
    }
}

/// Writes (or with `check` compares) every generated view. Returns findings;
/// generation stops before comparing or writing views when an artifact cannot
/// be collected, and refuses to overwrite an author-owned index.md.
pub fn run_index(root: &Path, check: bool) -> Vec<Finding> {
    let mut collection_findings = Vec::new();
    let (artifacts, collection_complete) = collect_artifacts(root, &mut collection_findings);
    if !collection_complete {
        return collection_findings;
    }
    let mut findings = Vec::new();
    if check {
        check_generated_views(root, &artifacts, &mut findings);
        return findings;
    }
    let expected_views = render_views(&artifacts);
    for committed in committed_views(root, &mut findings) {
        if !expected_views.contains_key(&committed)
            && let Err(error) = std::fs::remove_file(root.join(&committed))
        {
            findings.push(Finding::new(
                &committed,
                None,
                format!("cannot remove orphaned view: {error}"),
            ));
        }
    }
    for (path, content) in expected_views {
        if !output_path_is_safe(root, &path, &mut findings) {
            continue;
        }
        let target = root.join(&path);
        if path.ends_with("index.md")
            && let Ok(existing) = std::fs::read_to_string(&target)
            && !existing.starts_with(GENERATED_MARKER)
        {
            findings.push(Finding::new(
                &path,
                Some(1),
                "author-owned index.md must be removed before specful generates navigation here",
            ));
            continue;
        }
        if let Some(parent) = target.parent()
            && let Err(error) = std::fs::create_dir_all(parent)
        {
            findings.push(Finding::new(
                &path,
                None,
                format!("cannot create directory: {error}"),
            ));
            continue;
        }
        if let Err(error) = std::fs::write(&target, content) {
            findings.push(Finding::new(
                &path,
                None,
                format!("cannot write view: {error}"),
            ));
        }
    }
    findings
}

#[cfg(test)]
mod tests {
    use super::{CATALOG_PATH, render_views};
    use crate::repo::SPECS_DIR;

    #[test]
    fn renders_catalog_and_root_index_with_zero_artifacts() {
        let views = render_views(&[]);
        assert!(views.contains_key(CATALOG_PATH), "views: {views:?}");
        assert!(
            views.contains_key(&format!("{SPECS_DIR}/index.md")),
            "views: {views:?}"
        );
    }
}
