#!/usr/bin/env python3
"""Stub `specful` binary for hook-script tests: exit code and output are env-controlled."""

import os
import sys

output = os.environ.get("FAKE_SPECFUL_OUTPUT", "")
if output:
    print(output)
sys.exit(int(os.environ.get("FAKE_SPECFUL_EXIT", "0")))
